---
title: "Truth, Beauty, and Data:<br>Why Data Visualization Matters in Research"
author:
- name: Andrew Heiss, PhD
  affiliation: Georgia State University
  email: aheiss@gsu.edu
date: >-
  Methods workshop<br>
  Département de science politique<br>
  Université de Montréal<br><br>
  September 17, 2020<br>
output:
  html_document:
    theme: readable
    toc: yes
---

---

## Slides

<p><a class="btn btn-primary btn-lg" target="_blank" href="slides.html"><i class="fas fa-external-link-alt"></i> View all slides in new window</a> <a class="btn btn-primary btn-lg" target="_blank" href="andrew-heiss_umontreal-dataviz_2019-09-17.pdf" role="button"><i class="far fa-file-pdf"></i> Download PDF of all slides</a></p>

```{r embed-xaringan, echo=FALSE}
xaringanExtra::embed_xaringan(url = "slides.html", ratio = "16:9")
```

View the [R Markdown source for the slides at GitHub](https://github.com/andrewheiss/2020-09-17_umontreal-dataviz).

## Resources

### Data visualization

- Andrew Heiss, ["Data Visualization with R"](https://datavizm20.classes.andrewheiss.com/) (free online course)
- Kieran Healy, [ *Data Visualization for Social Science: A practical introduction with R and ggplot2*](http://socviz.co/)
- Claus Wilke, [*Fundamentals of Data Visualization*](https://clauswilke.com/dataviz/)
- Alberto Cairo, *The Truthful Art: Data, Charts, and Maps for Communication* 
- Stephanie D. H. Evergreen, *Effective Data Visualization: The Right Chart for the Right Data*
- Dona M. Wong, *The Wall Street Journal Guide to Information Graphics: The Dos and Don’ts of Presenting Data, Facts, and Figures* 
- Hadley Wickham and Garrett Grolemund, *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*
- Alberto Cairo, *The Functional Art: An Introduction to Information Graphics and Visualization*

### Accessibility

- [**Vischeck**](http://www.vischeck.com/vischeck/vischeckImage.php): Simulate how your images look for people with different forms of colorblindness (web-based)
- [**Color Oracle**](http://colororacle.org/index.html): Simulate how your images look for people with different forms of colorblindness (desktop-based, more types of colorblindness)

### Colors

- [**Adobe Color**](https://color.adobe.com): Create, share, and explore rule-based and custom color palettes.
- [**ColourLovers**](http://www.colourlovers.com/): Like Facebook for color palettes.
- [**viridis**](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html): Perceptually uniform color scales.
- [**Scientific Colour-Maps**](http://www.fabiocrameri.ch/colourmaps.php): Perceptually uniform color scales like viridis. Use them in R with [**scico**](https://github.com/thomasp85/scico).
- [**ColorBrewer**](http://colorbrewer2.org/): Sequential, diverging, and qualitative color palettes that take accessibility into account.
- [**Colorgorical**](http://vrl.cs.brown.edu/color): Create color palettes based on fancy mathematical rules for perceptual distance.
- [**Colorpicker for data**](http://tristen.ca/hcl-picker/): More fancy mathematical rules for color palettes ([explanation](https://www.vis4.net/blog/posts/avoid-equidistant-hsv-colors/)).
- [**iWantHue**](http://tools.medialab.sciences-po.fr/iwanthue/): Yet another perceptual distance-based color palette builder.
- [**Photochrome**](https://photochrome.io/): Word-based color palettes.
- [**PolicyViz Design Color Tools**](https://policyviz.com/better-presentations/design-resources/design-color-tools/): Large collection of useful color resources

### Fonts

- [**Google Fonts**](https://fonts.google.com/): Huge collection of free, well-made fonts.
- [**The Ultimate Collection of Google Font Pairings**](https://www.reliablepsd.com/ultimate-google-font-pairings/): A list of great, well-designed font pairings from all those fonts hosted by Google (for when you're looking for good contrasting or complementary fonts).

### Storytelling

- Ben Wellington, ["Making data mean more through storytelling"](https://www.youtube.com/watch?v=6xsvGYIxJok)
- Jonathan Schwabish, ["Better data communication"](https://vimeo.com/230757062)
- Cole Nussbaumer Knaflic, *Storytelling with Data: A Data Visualization Guide for Business Professionals*
- Alan Alda, *If I Understood You, Would I Have This Look on My Face? My Adventures in the Art and Science of Relating and Communicating*
- Nancy Duarte, *Resonate: Present Visual Stories That Transform Audiences*
